version: '3'
services:
  s3:
    hostname: s3
    image: minio/minio
    ports:
      - "9091:9000"
    environment:
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=password
    command: server /data
  pollster:
    image: carimura/pollster
    restart: always
    depends_on:
      - s3
    links:
      - "s3"
    environment:
      #S3_URL: "s3://admin:password@s3:9000/us-east-1/default-bucket"
      S3_URL: "http://admin:password@minio.ngrok.io/minio/default-bucket/"
      WEBHOOK_ENDPOINT: "http://carimura.ngrok.io/t/tools/image-to-slack"
      POLLSTER_BACKOFF: 5