version: '3'
services:
  # s3:
  #   hostname: s3
  #   image: minio/minio
  #   ports:
  #     - "9091:9000"
  #   environment:
  #     - MINIO_ACCESS_KEY=admin
  #     - MINIO_SECRET_KEY=password
  #   command: server /data
  pollster:
    image: carimura/pollster
    restart: always
    environment:
      REGION: "us-phoenix-1"
      BUCKET: "chad-test"
      STORAGE_URL: "ocimiddleware.compat.objectstorage.us-phoenix-1.oraclecloud.com"
      WEBHOOK_ENDPOINT: "http://carimura.ngrok.io/t/tools/image-to-slack"
      POLLSTER_BACKOFF: 5
      ACCESS_KEY_ID: $ACCESS_KEY
      SECRET_ACCESS_KEY: $SECRET_KEY